import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import Add from '../comps/Add_block'
import Footer from '../comps/Footer'
import Intro from '../comps/intro'
import Team from '../comps/Team'
import styles from '../styles/Home.module.scss'
import Router from 'next/router';
import Nav from '../comps/Nav'

export default function Home() {

  useEffect(() => {
    
  }, []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Safe Journey!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


     <Nav />

      <Intro />
      <Add />
      <Team />
      <Footer />



    </div>
  )
}
