import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import Add from "../comps/Add_block";
import Footer from "../comps/Footer";
import Intro from "../comps/intro";
import Team from "../comps/Team";
import styles from "../styles/Home.module.scss";
import Router from "next/router";
import Nav from "../comps/Nav";
import Button from "@mui/material/Button";
import { useRouter } from "next/router";
import Fade from "react-reveal/Fade";

import { useState } from "react";
import firebase from "../db/firebase";

export default function Home() {
  const [Userdata, setUserdata] = useState([]);
  const router = useRouter();

  useEffect(async () => {}, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Safe Journey!</title>
        <link rel="icon" href="icons/android-chrome-512x512.png" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Intro />
      {/* </Fade> */}
      <Fade bottom>
        <Add />
      </Fade>
      <Fade bottom>
        <Team />
      </Fade>
      <Footer />
    </div>
  );
}
